logging.level.net.fortuna.ical4j: INFO
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
      retries: 5
calendar:
   cache: /tmp/trash-calendar
   update: 59 39 */6 * * *
notification:
   telegram:
      polling: PT5M
      